### ISSUE TITLE
AttackChain.js (Suggestion)

### ISSUE THREAD

**Issue by panchokoster** [triacontane/RPGMakerMV#13]
Nice plugin! I will definitely use it! Just one suggestion: It would be great if the total amount of damage of the chain could also be shown on screen.

Regards!,
F.

**Comment by triacontane** [comment]
Hi. Thank you for using plugin!
I added function by your Suggestion.

https://github.com/triacontane/RPGMakerMV/blob/master/AttackChain.js

**Comment by panchokoster** [comment]
Thank you very much. It works great!
Regards!,
F.
