### ISSUE TITLE
HalfMove.js 1.11.3 において イベントが上下から近づく際にプレイヤーに隣接できない

### ISSUE THREAD

**Issue by elleonard** [triacontane/RPGMakerMV#19]
プレイヤーもイベントも移動ルートの設定コマンドで動かしており、プラグインパラメータの強制中無効がtrueになっている状態です。
この状態で移動ルートの設定コマンドを使用した際、イベントがy軸方向からプレイヤーに近づいて隣接することができません。

Game_EventのcanPassメソッドで偽が返ってしまうためで、原因を調べたところ以下の行が悪さをしているようでした。
https://github.com/triacontane/RPGMakerMV/blob/master/HalfMove.js#L1437

かなり複雑なプラグインになっていて、なぜ上下方向に判定を拡大した上で衝突判定を行っているのかわかりませんが、これとposUnitメソッドでの衝突判定範囲拡大を合わせると、上下方向に1マス分判定が広がります。
プレイヤーもイベントも半歩移動していないのに、イベントが上下方向からプレイヤーに隣接するマスに移動できなくなります。

該当の行が追加されたv1.6.0は半歩すり抜け禁止時のイベントからの接触トリガーを理由としたコミットだったようですが、歩行可能判定のための衝突とイベントトリガーのための接触を一緒くたに扱っているが故に起きている問題のように見受けられます。
`isCollidedFromPlayer` フラグはトリガー拡大が有効の場合のみ使用されているようなので、そこに注目して衝突と接触の判定を分離できれば良いのかなと思います。

**Comment by triacontane** [comment]
コメントありがとうございます！
こちらで引き続き調査してみます。

**Comment by elleonard** [comment]
こちらでも追加調査を行ってみたところ、ニューゲームを開始した後だと接触判定が正常になりました。
HalfMoveを導入する前のセーブデータをロードすると、プレイヤーの半歩すり抜け禁止フラグ（`$gamePlayer._throughDisable`）が`undefined`になってしまうことが原因のようです。

`_throughDisable`をニューゲーム開始時に偽で初期化するが、セーブデータに存在しない場合は`undefined`として扱っているために挙動が食い違っているものと思われます。
（`isThroughEnable` メソッドで `_throughDisable=undefined` ならプラグインパラメータの値を使用する記述があります）

フラグの意味的には `isThroughEnable` の処理は正しいように見えますが、これだとニューゲーム開始後はプラグインパラメータの値に関わらず、半歩すり抜けが許可されているように見えます。

半歩すり抜けを禁止した時に上下からイベントが隣接できないのはやはり、衝突判定範囲の拡大に原因があるような気がします。

**Comment by elleonard** [comment]
追記
半歩すり抜け禁止フラグはプレイヤーに付随するものではなく、イベントに付随するものという仕様のようなので、プレイヤーの`_throughDisable`が常に偽なのは正しいのかもしれません。

そう解釈するのであれば、今の`isThroughEnable` メソッドの定義を`Game_Event`側に再定義して、`Game_CharacterBase`の定義では必ず偽を返す（`Game_CharacterBase`の`_throughDisable`フラグを廃止する）という修正だけで良いかもしれません。
……可読性を考えるとこういった複雑な仕様はコメントにしておきたいですが。

**Comment by triacontane** [comment]
お疲れさまです。
「ニューゲームを開始した後だと接触判定が正常になる」とのことから、ロード完了時にプレイヤーの半歩関連プロパティが定義されていなければ初期化する処理を追加しました。

現状の実装にできるだけ影響を与えたくないのと、JSにおける擬似的なオーバーライドが分かりにくく多用しづらい点を考慮し、_throughDisableフラグには必ずtrue/falseが入っているようにします。

**Comment by elleonard** [comment]
ご対応ありがとうございます！
現状できる最も手軽で効果的な対応だと思います。 👍
