### ISSUE TITLE
How to add Fullscreen button in webpage?

### ISSUE THREAD

**Issue by RyanBram** [triacontane/RPGMakerMV#31]
Hi, Triacontane. Greetings.
My name is Ryan.

Thank you for creating so many useful plugin and thank you for many tips that you wrote in your blog. I cannot speak Japanese, therefore I use Google Translate to read your articles.

Based on your article here: https://triacontane.blogspot.com/2016/06/rpgmv.html you wrote a very useful tips for me. But there are some features that was missing in your article:

1. How to make RPG Maker game screen fit automatically to the iframe window without pressing F3?
2. How to make a button that will toggle the game into fullscreen mode?
3. How to disable ESC button to escape full screen, but using F11 instead? Because ESC is used to toggle menu in RPG MV game.

Fortunately, I found solution number 1 and 2. By using this script 
[Fullscreen_Options.zip](https://github.com/triacontane/RPGMakerMV/files/3353084/Fullscreen_Options.zip)
I can disable F3 and make the game screen automatically fit the screen. I can also use F4 to fullscreen the iframe window.

The problem is number 3. When going fullscreen, the ESC button will escape fullscreen mode.

Do you have any solution for this?

For information this is my web https://www.rumahpintar.org/2019/07/membuat-game-berbasis-html5.html

I am sorry if I bother you.

**Comment by triacontane** [comment]
Hi, RyanBram. Greetings.

It is browser specification to return from full screen by ESC.
I think that it is difficult to prohibit this specification .
It is possible to disable the function of ESC key from MV. Players use the X key instead.

https://gist.github.com/triacontane/9049e97f4f2f4caa638ff762d8e68b03

**Comment by RyanBram** [comment]
Hi.
Thank you very much for the solutions about ESC key.
