### ISSUE TITLE
Conflict HalfMove.js and TemplateEvent.js

### ISSUE THREAD

**Issue by Eliaquim-RK0** [triacontane/RPGMakerMV#33]
Hi there.
I'm using these two plugins in my project. But it seems that some note tags from HalfMove.js don't work with Template Events.
I have a Template Event in the Template Map.
Then I put him in another map with the note tags:
`<TE:Buraco><HMTriggerExpansion:ON><HMExpansionArea:1.5,0,1.5,0>`
But the Expansion trigger doenst work.
I also tried to put the Expansion Trigger in the note tag of the Template Event in the Template map, then call the event only with:
`<TE:Buraco>`
But doenst seem to work either.
I swap the order in the plugin manager, but no results.
Thanks for your great plugins. I learn a lot from the codes ^^

**Comment by triacontane** [comment]
Hello!
Thank you for using the plug-in.

I tested with two plugins here and it worked fine.

- Map Event Note
<TE:Buraco>

- Template Tevent Note(name:Buraco)
<HMTriggerExpansion:ON><HMExpansionArea:1.5,0,1.5,0>

Will the problem also occur if you have the two plug-ins up to date and try them in a new project?

Thank you.

**Comment by Eliaquim-RK0** [comment]
Ohhh! I'm so sorry... Now that I made the test, it seems that I forgot to change the parameters to Integrate the note tags. When I change to "Integrate", it work fine!
Sorry for make you lost your time :(

**Comment by triacontane** [comment]
Fine. I'm glad to resolve :)
