### ISSUE TITLE
Dtexpicture real time mode conflict with yanfly plugin

### ISSUE THREAD

**Issue by pasunnaniyay** [triacontane/RPGMakerMV#34]
with this plugin
http://www.yanfly.moe/wiki/Plugin_Commands_-_Switches_%26_Variables_Access_(YEP)
the real time mode is not working
I had attach fresh project with only two plugin
https://drive.google.com/open?id=1GQNPKDJHGs4X_7KvCy8J7qMkxMrlsKOt

I think it had problem with \v[] and v[]
just report 
if you don't want to fix this, never mind
thank you

**Comment by triacontane** [comment]
Hi.
Thanks you for using plugin.

I checked the phenomenon here and fixed it.
https://github.com/triacontane/RPGMakerMV/blob/master/DTextPicture.js

Please place DTextPicture.js under YEP_PluginCmdSwVar.js.
