### ISSUE TITLE
EventReSpawn - Variables in Plugin Commands

### ISSUE THREAD

**Issue by Eliaquim-RK0** [triacontane/RPGMakerMV#37]
Hi Triacontane!
This is not an issue, but I want to ask if you can add the possibility to use variables in plugin commands.
Ex:
ERS_MAKE_TEMPLATE 1 V25 V26
Thanks anyway ^^

**Comment by triacontane** [comment]
Hi.
Thank you for using my plugin.

If you want to use a variable, specify a escape character like a 'Show Text'
However, there is a possibility of conflict if used simultaneously with the YEP plug-in.

Ex : 
ERS_MAKE_TEMPLATE 1 \V[25] \V[26]

**Comment by Eliaquim-RK0** [comment]
Oh.. I never though about the use of escape characters. I will try it later and let you know.
Your work is great! Thank you.
