### ISSUE TITLE
Better use for touch control in ChangeWindowTouchPolicy.js for MV [Suggestion]

### ISSUE THREAD

**Issue by RyanBram** [triacontane/RPGMakerMV#43]
Hi, Triacontane.

Your ChangeWindowTouchPolicy.js is really awesome, especially when combined with MousePointerExtend.js which will greatly improves mouse user experience.

I have some suggestions to improve ChangeWindowTouchPolicy.js for touchscreen user:

1. Add option for touch user to perform only single touch for selecting menu/command. Currently, touch user need to touch the menu/command two times. First touch for highlighting the menu/command, second is for selecting the menu/command which means too many touch to perform a command.

2. Skip "Cursor" sound when touching the menu/command, and just play the "Ok" sound, because every single touch will be registered as selection (as Ok).

3. Add ability to swipe up and down to scroll long list of menu/command.

Thank you for your attention.

**Comment by triacontane** [comment]
Hello!
Sorry for the late reply.

Some of your suggestions seem to be resolved with the use of RPGMakerMZ.
We are currently too busy porting plugins for MZ to deal with them.
Sorry.

**Comment by RyanBram** [comment]
Hi.
Thank you very much for the solution.

Thank you very much for being a developer who is still active until MZ era, when there are currently many developers who are no longer active in RPG Maker scene.

Really sorry for taking your time.
