### ISSUE TITLE
HalfMove 1 tile y-axis

### ISSUE THREAD

**Issue by ahb0327** [triacontane/RPGMakerMV#52]
![image](https://user-images.githubusercontent.com/12953393/107139839-9ce61280-6961-11eb-9ac6-56f713d05e1f.png)
Current situation.
![image](https://user-images.githubusercontent.com/12953393/107139861-b1c2a600-6961-11eb-9486-be752f92ad2f.png)
I can move up half tile.
![GIF 2021-02-07 오후 4-33-56](https://user-images.githubusercontent.com/12953393/107139967-5349f780-6962-11eb-8a05-194222c9d3b0.gif)
But in this situation of all tiles, I don't want to move up and down. I tried modifying Game_CharacterBase.isMapPassable but it doesn't work as I want. Where should I modify it?

**Comment by triacontane** [comment]
Hello!
Thank you for using the plugin.

Unfortunately, HalfMove.js is coded based on the above specifications, so it would require a major overhaul of the code in order to achieve your request.
