### ISSUE TITLE
MZ上のTitleNewGameOnly.jsでfileExistAction 2の時にマップの自動更新が機能しない

### ISSUE THREAD

**Issue by ayamada** [triacontane/RPGMakerMV#56]
ものすごく限定的なのですが、「MZ上」かつ「fileExistAction 2」の時に、セーブデータを作り、その後にゲーム本体の方をツクールエディタ上で更新してセーブを行ったマップ上に新しいイベントを追加したり元あったイベントを削除すると、そのセーブデータをロードした際に、追加した筈のイベントがまだなかったり(同じマップに入り直すと出現します)、削除されたイベントを参照しようとして例外が出たりします。

本来なら、そのような状況になると [onLoadSuccess()](https://github.com/triacontane/RPGMakerMV/blob/629954f988c62ca06fa604140d8efe297d060038/TitleNewGameOnly.js#L200)の中にある `Scene_Load.prototype.reloadMapIfUpdated` がゲームデータの更新を検知してロード直後に今いるマップの再読み込みを行ってくれるのでよかったのですが、これが何故かMZでは動いておらず(MVでは動いています)、どうしてか調べました。

MVでは `DataManager.loadGame()` は真偽値を返すのですが、 MZでは `DataManager.loadGame()` はPromiseを返すように変更になっており(つまりロード処理が即座には完了しないという事です…)、そのせいでロード完了前の何かよくわからないものを参照して「ゲームデータは更新されていない」と判定されているみたいな雰囲気でした。

ここの[loadGame()を実行している箇所](https://github.com/triacontane/RPGMakerMV/blob/629954f988c62ca06fa604140d8efe297d060038/TitleNewGameOnly.js#L197)を以下のようにすると、きちんとロード後の自動更新が機能するようになったようです(then回りの処理はMZ本体の `Scene_Load.prototype.executeLoad` を参考にしました)。

```
                this._sceneLoad = new Scene_Load();
                var t = this;
                DataManager.loadGame(DataManager.latestSavefileId())
                .then(function () {
                    t._sceneLoad.onLoadSuccess();
                    t.fadeOutAll();
                }).catch(() => t._sceneLoad.onLoadFailure());
```

最初これでPRを作ろうと思ったのですが、このようにすると当然MVでは動かなくなるので、PRにするにはその辺りのきちんとした対応が必要そうなので、とりあえずIssueとして報告させていただきます。すみません。

**Comment by triacontane** [comment]
こんにちは！
ご報告ありがとうございます。
現在、MVプラグインのMZ向け移植は以下のブランチで開発を進めております。
https://github.com/triacontane/RPGMakerMV/tree/mz_master

TitleNewGameOnly.jsについては正式な移植作業が完了していないため、ご指摘の問題に留意の上で移植作業を進めたいと思います。

**Comment by ayamada** [comment]
なるほどです、そうだったんですね。どうもありがとうございます！
どうかよろしくお願いいたします！

**Comment by triacontane** [comment]
TitleNewGameOnly.jsについて、移植作業が完了しました。
よろしければお試しください。

https://github.com/triacontane/RPGMakerMV/blob/mz_master/TitleNewGameOnly.js

**Comment by ayamada** [comment]
対応どうもありがとうございます！
こちらの新しいバージョン導入させていただきました。
ゲーム更新後のロード時に、マップの自動リロードがきちんと動作しているのを確認できました。
どうもありがとうございました！
