### ISSUE TITLE
When Critical Hit and Weak/Resist/Guard hit occur, Critical Hit picture/text not showing

### ISSUE THREAD

**Issue by fernando122** [triacontane/RPGMakerMV#58]
On plugin BattleEffectPopup.js

It only show Weak/Resist/Guard if critical hit happen.

**Comment by triacontane** [comment]
Hi!
Please wait a moment while I check the issue.

**Comment by triacontane** [comment]
Hello!
I tried it here, but I could not reproduce the phenomenon you reported.
It may be a conflict with other plugins.

**Comment by fernando122** [comment]
Hello
The last update actually fixes the problem, Thanks you! :)
