### ISSUE TITLE
ChangeWindowTouchPolicy.js doesn't work in Core v1.3.2

### ISSUE THREAD

**Issue by RyanBram** [triacontane/RPGMakerMV#59]
こんにちはトリアコンタン、
プロジェクトをMVからMZに移行しました。

私が使用しているプラグインの1つは、ChangeWindowTouchPolicy.jsです。 ただし、プラグインのMZバージョンを試すと、次のエラーメッセージが表示されます。
![ChangeWindowTouchPolicy error](https://user-images.githubusercontent.com/4508389/125157384-e34fcf80-e194-11eb-8aeb-21d3fe1036c1.jpg)

このメッセージは、他のプラグインがインストールされていない新しいプロジェクトで試したにもかかわらず表示されます。

ご清聴ありがとうございました。

**Comment by triacontane** [comment]
こんにちは！
プラグインを使ってくださり、ありがとうございます。

残念ですが、ChangeWindowTouchPolicy.jsはMZでは動作しません。
このプラグインのMV版は、2回タッチしないとウィンドウの項目を選択できない問題を解決するために作られました。
MZではこの問題は解決したので、今のところ当プラグインは移植の予定はありません。

すみません。ご了承ください。

**Comment by RyanBram** [comment]
この問題でごめんなさい。

このプラグインはmz_masterブランチで見たので、MZをサポートしていると思いました。
MZで完璧ではないことの1つは、Windowsでタッチスクリーンを使用するときにメニューを2回タッチする必要があることです。 ChangeWindowTouchPolicy.jsのMVバージョンでは、以下を削除する必要がありました。
`Utils.isMobileDevice() &&`
から
`if (Utils.isMobileDevice() && this.isCursorMovable())`。

明確にしていただきありがとうございます。ご迷惑をおかけして申し訳ありません。
