### ISSUE TITLE
PressAnyButton.js のMZ版で フォント情報を指定するとエラーが発生する

### ISSUE THREAD

**Issue by pota-gon** [triacontane/RPGMakerMV#63]
PressAnyButton.js のMZ版でフォントを指定し、
fonts フォルダに指定した ttf などのフォントデータを配置すると以下エラーが発生しました。

ReferenceError
fontFace is not defined

下記の、修正後のソース(fontFace は存在しないので、font.Face に変更)では、
エラーが発生しませんでした。お手数ですが、ご確認よろしくお願い致します。

・修正前(266行目)
```js
this.bitmap.fontFace = fontFace;
```

・修正後(266行目)
```js
this.bitmap.fontFace = font.Face;
```

**Comment by pota-gon** [comment]
上記では、エラーがでなくなるようですが、
font.name を指定することで、動くようです。
ご確認の程よろしくお願いいたします。

**Comment by triacontane** [comment]
こんにちは！
ご報告ありがとうございます。
こちらで現象を確認、修正しました。

**Comment by pota-gon** [comment]
早急な対応ありがとうございます!
修正後、フォントが正しく適用されることを確認しましたので、チケットは、Closeします。
