### ISSUE TITLE
CharacterGraphicExtend.js の敵キャラの色相指定について

### ISSUE THREAD

**Issue by pota-gon** [triacontane/RPGMakerMV#64]
CharacterGraphicExtend.js の色相についてバグと見られる動きがあったので報告致します。 
<CG敵キャラ:（ページ数）,（ファイル名）,（色相）>

RPGツクールMZ の機能との認識ですが、
Dragon の色相、例えば 60 を指定すると、データベースでは黄色のドラゴンになるのですが、
以下のようにイベントへ設定するとイベントの画像は紫のドラゴンとなってしまいます。
<CG敵キャラ: 1,Dragon,60>

恐らく、ソースの以下部分で、hue をマイナス値に
設定しているのが原因ではないかと推測されます。

・792 行目
```js
                this.setHue(-hue);
```

本件、追加された経緯を存じていないため、
仕様ということであれば、チケットは close していただければと思います。

**Comment by triacontane** [comment]
こんにちは！
ご連絡ありがとうございます。

こちらで確認したところ、`this.setHue(-hue);`は誤りでした。
MV版と比較しても異なる色になっていたため修正しました。
https://github.com/triacontane/RPGMakerMV/commit/ea8e12e340fd203f72cbbd3124f41c112a4d6915#diff-565bdd90fdeed72ea68fa4d796dea3e821fdf7277449b815ec854a1437a67907

**Comment by pota-gon** [comment]
修正ありがとうございます。
確認致しました。Closeします。
