### ISSUE TITLE
HalfMove.js for RPG MV - Can't move when using different tile unit

### ISSUE THREAD

**Issue by Bass2yang** [triacontane/RPGMakerMV#70]
Hello! 

The plugin works great with Chrono Engine. Is it possible to use less that 0.5 Game_Map.tileUnit? Right now, if I change it to 0.25, I am only able to move once, and then I get stuck; the player is unable to move. However, if I hold down the "Ctrl" key to override the passability (I think this turns on the "THROUGH" function for the player), I can move at the 0.25 tile (though the character animation is also slower).

Any assistance on this is greatly appreciated!

**Comment by triacontane** [comment]
Hello!
Thank you for using our plugin.

Game_Map.tileUnit value is fixed at 0.5. It cannot be changed.
It would be preferable to be able to change it, but we found it difficult during implementation.
