### ISSUE TITLE
Is Chronus plugin mz and mv versions different?

### ISSUE THREAD

**Issue by arrosev** [triacontane/RPGMakerMV#75]
Hi, triacontane, I want to use the Chronus plugin on my RPGMaker MV, but I found that Chronus in mz_master branch has recently fixed some issues, and Chronus in the master branch has not been updated for a long time, should I use Chronus from the master branch or Chronus from mz_master branch? My software is RPGMaker MV, and although I saw that the documentation says that MV should use the master branch, I'm not sure, please help me...

**Comment by triacontane** [comment]
Hello!

Thank you for using our plugin.

We recommend using the MV version (master branch).
MZ version (master_mz branch) may not work properly in MV.

We only report bugs and add features to the reported version of the plugin.
If there is no report, we just do not respond to it, but we do not stop updating it.

If there is a critical bug, we also fix the MV version using cherry-picking.

**Comment by arrosev** [comment]
Ok, thanks for your contribution to the open source community
