### ISSUE TITLE
 DevToolsManage.js parameter locale bug

### ISSUE THREAD

**Issue by moonyoulove** [triacontane/RPGMakerMV#76]
Nice plugin! However, there is a difference between Japanese and English in the parameters of the latest version.

DevToolsManage.js v1.2.0

 * @param CutTitle
 * @text タイトルカット
 * @desc タイトル画面をとばしてゲームを開始します。
 * @default 0
 * @type select
 * @option 無効
 * @value 0
 * @option ニューゲーム開始
 * @value 1
 * @option 最新データをロード
 * @value 2

**Comment by triacontane** [comment]
Hello!
Thank you for using our plugin.

We have fixed the issue you mentioned.

https://github.com/triacontane/RPGMakerMV/blob/559382072dca2c4a9065a584d7d4241395d5cbbb/DevToolsManage.js#L19
