### ISSUE TITLE
Does the ExtraWindow.js plugin have a way to adjust window and text styles?

### ISSUE THREAD

**Issue by arrosev** [triacontane/RPGMakerMV#77]
I want to adjust the color and position of "Displayed Text", such as placing the font in the middle of the window, and removing the white border of the window. Even if it is by code, please let me know.

**Comment by triacontane** [comment]
Hello!
ExtraWindow.js is an officially provided plugin and is not maintained in this repository.

If you want to modify the text color and alignment, the drawAllText method around line 330 is applicable.

**Comment by arrosev** [comment]
> Hello! ExtraWindow.js is an officially provided plugin and is not maintained in this repository.
> 
> If you want to modify the text color and alignment, the drawAllText method around line 330 is applicable.

Sorry, I saw that this plug-in seems to be written by you. I checked its code at noon and found that there are two instance methods for drawing text, one of which has an align attribute, and also found in Window_Base to modify the text color Instance methods, I should just have to override them, thanks for getting back to me.
