### ISSUE TITLE
MasterVolumeOption in MZ

### ISSUE THREAD

**Issue by Nathan-MV** [triacontane/RPGMakerMV#78]
I thought it would work fine, but I can't change the volume...
![image](https://github.com/triacontane/RPGMakerMV/assets/67521199/212572ab-1a27-4a3a-8ad3-35e2e79a9a53)

**Comment by triacontane** [comment]
Hello!

This plugin is not MZ ported.
It was just copied from the branch for MV.

We are currently in the process of porting it in phases based on requests and usage.

We have done some research and found that it is easy to port this time, so we have ported it.

https://github.com/triacontane/RPGMakerMV/blob/mz_master/MasterVolumeOption.js

**Comment by Nathan-MV** [comment]
> Hello!
> 
> This plugin is not MZ ported. It was just copied from the branch for MV.
> 
> We are currently in the process of porting it in phases based on requests and usage.
> 
> We have done some research and found that it is easy to port this time, so we have ported it.
> 
> https://github.com/triacontane/RPGMakerMV/blob/mz_master/MasterVolumeOption.js

Thanks!!!
