### ISSUE TITLE
StartUpFullScreen in MZ

### ISSUE THREAD

**Issue by Nathan-MV** [triacontane/RPGMakerMV#79]
Can we make it full screen the exact moment we set it to On in Window_Options? (I am aware that we can instantly toggle between On and Off with F4, but players don't know)

**Comment by triacontane** [comment]
Added setting to change full screen status immediately upon option change.

https://github.com/triacontane/RPGMakerMV/commit/2aec3563249432f5ef465a494cc4719eb5e92873
https://github.com/triacontane/ElectronForMz/commit/a1618a06accf5b93953adfea7901c34028992ce8

**Comment by Nathan-MV** [comment]
> Added setting to change full screen status immediately upon option change.
> 
> [2aec356](https://github.com/triacontane/RPGMakerMV/commit/2aec3563249432f5ef465a494cc4719eb5e92873) [triacontane/ElectronForMz@a1618a0](https://github.com/triacontane/ElectronForMz/commit/a1618a06accf5b93953adfea7901c34028992ce8)

I appreciate it, thank you!!
