### ISSUE TITLE
[Request] Window Option Screen Scale

### ISSUE THREAD

**Issue by Nathan-MV** [triacontane/RPGMakerMV#80]
When you have time or interest it would be cool a simple plugin for screen scaling changing to window option, let's say the game is using sprites made for a 320x180 screen and scaling them 2x for 640x360 and 4x for 1280x720. A parameter to show the scale times or the resolution that will be changed would be nice, as well as compatibility with the electron window

**Comment by triacontane** [comment]
Hello!
Thank you for your request!

However, we do not have much time available to create new plugins, so it is difficult to respond to your request.
