### ISSUE TITLE
CustomizeConfigItem in MZ

### ISSUE THREAD

**Issue by Nathan-MV** [triacontane/RPGMakerMV#81]
![image](https://github.com/triacontane/RPGMakerMV/assets/67521199/259042d3-bb12-41e1-af70-45e9d06bc408)
![image](https://github.com/triacontane/RPGMakerMV/assets/67521199/a651c1fe-76e2-41ce-ac93-ed381a21bb21)

**Comment by triacontane** [comment]
Hello!
We checked here and did not find any problem.

This plug-in has not been translated into English.
It may be that the version when translated into English is out of date.
The latest version is 3.2.0.

![image](https://github.com/triacontane/RPGMakerMV/assets/15870635/22c8f18a-bce2-4dd3-9f59-b117d7a714dd)
