### ISSUE TITLE
add feature for supporting exporting all map event in RPGツクールMVツール・データベースコンバーターMV

### ISSUE THREAD

**Issue by The-fthe** [triacontane/RPGMakerMV#82]
Hello,
RPGツクールMVツール・データベースコンバーターMV
I've found your tools extremely helpful for our game's localization. Could the plugin be enhanced to export all map events like it does for command events? We have over 100 map events, and this feature would be a great aid.

Thank you for considering.
![image](https://github.com/triacontane/RPGMakerMV/assets/61517693/6422652b-8709-4521-86e8-8e38f2f1e1dd)

**Comment by triacontane** [comment]
Hello!
Thank you for using the tool I created.

However, since this tool was delivered to the Maker official, I cannot add any functionality to it.
Sorry.
