### ISSUE TITLE
SceneGlossary with VisuMZ_1_MessageCore

### ISSUE THREAD

**Issue by ooooooonfdfasn** [triacontane/RPGMakerMV#83]
When using SceneGlossary and VisuMZ_1_MessageCore together, an error occurs the moment I open SceneGlossary's window.

To test it, I created a new MZ project, created the simplest event, and ran it.

![스크린샷 2023-11-21 211715](https://github.com/triacontane/RPGMakerMV/assets/115334429/c2dfec46-ed3e-44f7-91fd-513663cc4c98)
![스크린샷 2023-11-21 210206](https://github.com/triacontane/RPGMakerMV/assets/115334429/85100d0a-0d9c-47ff-bd07-4d1e7d8ef6b7)
![스크린샷 2023-11-21 210215](https://github.com/triacontane/RPGMakerMV/assets/115334429/36e86e33-c19e-4029-bbe8-9ce857e43ec2)

this is plugin order

![스크린샷 2023-11-21 210227](https://github.com/triacontane/RPGMakerMV/assets/115334429/9e1d9f1f-5d08-4586-b544-4421c8ae4403)

this is event

**Comment by triacontane** [comment]
Hello!
I checked and VisuMZ_1_MessageCore is obfuscated.
Therefore, it is difficult to support conflict investigation.

We will not be responding to this issue.

**Comment by Mouradif** [comment]
VisuStella is the opposite of Open Source. I hate them from the bottom of my heart
