### ISSUE TITLE
A small issue with the DynamicEquipParam

### ISSUE THREAD

**Issue by Nothentai** [triacontane/RPGMakerMV#84]
a.special('aaa') # メモ欄の[aaa]の値(※)
----
The above attribute seems to be invalid, I have already noted it in the armor<aaa: 100>
After I set it this way, the value immediately became invalid.

example:<DEP_攻撃力:50+a.special('aaa')>

**Comment by triacontane** [comment]
Hello!
We have identified the problem here and have fixed it.

https://github.com/triacontane/RPGMakerMV/commit/413deff67c3d2d503405c63ddd173f223269c752
