### ISSUE TITLE
再生値の固定化プラグイン(RegenerationFixed.js) のURLが違う

### ISSUE THREAD

**Issue by pota-gon** [triacontane/RPGMakerMV#86]
些細な問題なので、報告するか迷ったのですが、報告しておきます。
再生値の固定化プラグイン(RegenerationFixed.js) のVer1.0.1 にてURLが間違っていました。
d を t と間違えたものと推察します。優先度は、かなり低いので対応せずにCloseして頂いても構いません。

・間違ったURL(20行目)
```js
@url https://github.com/triacontane/RPGMakerMV/tree/mz_master/RegenerationFixet.js
```

・正しいURL(20行目)
```js
@url https://github.com/triacontane/RPGMakerMV/tree/mz_master/RegenerationFixed.js
```

**Comment by triacontane** [comment]
こんにちは！
ご報告ありがとうございます。
以下のコミットで修正しました。

https://github.com/triacontane/RPGMakerMV/commit/c8a1077e43f3b0126ef8b0d668105df79a8bf8e4

**Comment by pota-gon** [comment]
修正ありがとうございます！
Close致します。
