### ISSUE TITLE
SceneCustomMenu.js，このプラグインは携帯電話に対応していませんか

### ISSUE THREAD

**Issue by acgh14** [triacontane/RPGMakerMV#90]

**Comment by triacontane** [comment]
こんにちは！
本プラグイン自体にPC専用の機能はありません。
ただし、モバイル端末で操作する場合、Shiftキーなどはありませんのでご注意ください。
---
Hello!
This plug-in itself does not have any PC-specific functions.
However, please note that there is no Shift key, etc. when operating on a mobile device.
